url: http://gothamcity.freifunk.net/

community:
  # Metadata
  name: "Gotham City"
  meta: "Marvel"
  country: "MC"

  # Custom URLs
  url_wiki:  "/wiki"
  url_geomap: "/map/geomap.html"
  url_graph: "/map/graph.html"
  url_nodelist: "/wiki/Knoten"
  url_mailman: "http://lists.gothamcity.freifunk.net/mailman/listinfo/list"

  # Mail Contacts
  mail_info: "info@gothamcity.freifunk.net"
  mail_keys: "keys@gothamcity.freifunk.net"
  mail_discussion: "discussion@gothamcity.freifunk.net"

  # Other Contacts
  sip: ["space@sip.ffgc", "space@10.35.0.1"] # Optional
  twitter: "FreiFunkGothamCity" # Optional
  irc: "ircs://irc.hackint.net/ffgc"

  # GPS
  geo_lat: 40.5
  geo_lon: -74.1

firmware:
  base: "http://gothamcity.freifunk.net/firmware/stable/"
  type: "gluon"

  # URL to the site repo (gitweb,github...)
  gluon_site: "https://github.com/freifunk-gothamcity/site-ffgc"
  # Path to local checkout of the site repo
  gluon_site_dir: "../gluon/site"

tld:
  label: "ffgc"
  ns:
    - "10.35.0.1"
    - "fd35:f308:a922::ff00"
    - "10.35.5.1"
    - "fd35:f308:a922::ff01"
    - "10.35.10.1"
    - "fd35:f308:a922::ff02"
    - "10.35.15.1"
    - "fd35:f308:a922::ff03"
    - "10.35.20.1"
    - "fd35:f308:a922::ff04"
